from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.sparse import csr_matrix
from sklearn.decomposition import TruncatedSVD
import numpy as np
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import normalize
from collections import Counter

class DocumentClusterer():
    """
    Cluster documents using a classical bag-of-words pipeline.

    The pipeline runs in three stages:
        1. TF-IDF vectorisation turns raw text into a sparse term-document
           matrix weighted by inverse document frequency.
        2. Truncated SVD (Latent Semantic Analysis) projects that sparse
           matrix into a dense, lower-dimensional space that captures the
           dominant semantic axes and discards noise.
        3. Agglomerative (hierarchical) clustering merges documents
           bottom-up until the linkage distance exceeds dist_threshold.

    This pipeline is fast, fully reproducible given a random_state, and
    works well when documents are distinguished by distinctive vocabulary
    (e.g. legal contracts where "license", "franchise", "supply" carry
    strong signal). It is a weaker fit when documents share vocabulary
    but differ in meaning, which is where dense sentence embeddings tend
    to win.

    Attributes set by `fit`:
        tfidf_ (TfidfVectorizer): The fitted TF-IDF vectoriser.
        tdm_ (csr_matrix): The sparse term-document matrix.
        svd_ (TruncatedSVD): The fitted SVD reducer.
        fdm_ (np.ndarray): The L2-normalised reduced document matrix.
        labels_ (list[int]): Cluster label per document, aligned to doc_ids_.
        doc_ids_ (list): Document identifiers in the order they were fitted.
        silhouette_ (float): Cosine silhouette score over the reduced space.
    """
    def __init__(self,
                ngram: tuple,
                n_components: int,
                n_iter: int,
                dist_threshold: float,
                linkage: str,
                metric: str,
                input_type: str,
                random_state: int):
        
        self.ngram_range = ngram
        self.n_components = n_components
        self.n_iter = n_iter
        self.dist_threshold = dist_threshold
        self.linkage = linkage
        self.metric = metric
        self.input_type = input_type
        self.random_state = random_state

        self.tfidf_ = None
        self.svd_ = None
        self.labels_ = None
        self.doc_ids_ = None

    def tfidf_vectorizer(self, documents: dict) -> csr_matrix:
        """
        Generates a Term-Document Matrix (tdm) using TF-IDF vectorization.

        This method converts a collection of raw legal documents into a sparse matrix
        representing the importance of words and n-grams across the dataset.
        Vectorizer settings (input_type, ngram range) are taken from instance attributes.

        Args:
            documents (dict): A dictionary where keys are document identifiers
            and values are the document content, filenames, or file objects,
            depending on self.input_type.

        Returns:
            scipy.sparse.csr_matrix: A Compressed Sparse Row matrix where rows
            are documents and columns are TF-IDF weighted features.

        Side effects:
            Sets self.tfidf_ to the fitted TfidfVectorizer instance.
        """
        self.tfidf_ = TfidfVectorizer(input = self.input_type,
                                    ngram_range = self.ngram_range,
                                    stop_words='english')
        
        # tdm is the term-document matrix
        self.tdm_ = self.tfidf_.fit_transform(documents.values())
        
        return self.tdm_
    
    def dim_reduction(self, term_doc_matrix:  csr_matrix) -> np.ndarray:
        '''
        Performs dimensionality reduction using Truncated SVD (Latent Semantic Analysis).

        This method reduces the high-dimensional TF-IDF matrix into a lower-dimensional
        dense representation, capturing the underlying latent topics of the documents
        while removing noise and redundancy. The number of components is clamped to
        min(self.n_components, n_features - 1) to satisfy SVD constraints.
        Reduction settings (n_components, n_iter, random_state) are taken from
        instance attributes.

        Args:
            term_doc_matrix (csr_matrix): The sparse TF-IDF matrix generated by
            tfidf_vectorizer, of shape (n_documents, n_features).

        Returns:
            np.ndarray: A dense array of shape (n_documents, safe_dim) representing
            the documents in the reduced semantic space, where safe_dim is
            min(self.n_components, n_features - 1).

        Side effects:
            Sets self.svd_ to the fitted TruncatedSVD instance.
    '''
        safe_dim = min(self.n_components, term_doc_matrix.shape[1] - 1)

        self.svd_ = TruncatedSVD(n_components = safe_dim, 
                           n_iter = self.n_iter, 
                           random_state = self.random_state)
        
        # fdm is the frequency-document matrix
        self.fdm_ = self.svd_.fit_transform(term_doc_matrix)
        self.fdm_ = normalize(self.fdm_, norm='l2')

        return self.fdm_

    def clusterer(self, freq_doc_matrix: np.ndarray) -> np.ndarray:
        """
        Clusters documents using Agglomerative (hierarchical) Clustering.

        Groups documents hierarchically by merging clusters bottom-up until the
        linkage distance exceeds self.dist_threshold. Clustering settings
        (dist_threshold, linkage) are taken from instance attributes.

        Args:
            freq_doc_matrix (np.ndarray): Dense document matrix from dim_reduction,
            of shape (n_documents, n_components).

        Returns:
            np.ndarray: An array of integer cluster labels of shape (n_documents,),
            where each value identifies the cluster a document belongs to.

        Note:
            "ward" linkage only supports Euclidean distance. Using it with a
            different distance metric will raise a ValueError.
        """
    
        model = AgglomerativeClustering(n_clusters=None,
                                        metric=self.metric,
                                        distance_threshold = self.dist_threshold ,
                                        linkage = self.linkage)
        
        cluster_labels = model.fit_predict(freq_doc_matrix)

        return cluster_labels
    
    def fit(self, documents: dict) -> dict:
        """
        Runs the full pipeline on a collection of documents.

        Args:
            documents (dict): Keys are document identifiers, values are
                raw text strings (or file paths, depending on input_type).

        Returns:
            dict: A mapping of document identifier -> cluster label.
        """
        self.doc_ids_ = list(documents.keys())

        tdm = self.tfidf_vectorizer(documents)
        fdm = self.dim_reduction(tdm)
        self.labels_ = self.clusterer(fdm)
        self.labels_ = [int(l) for l in self.labels_]
        sizes = Counter(self.labels_)

        self.silhouette_ = silhouette_score(fdm, self.labels_, metric=self.metric)

        # useful metrics
        print(f"Silhouette Score: {self.silhouette_:.4f}")
        print(f"Number of Cluster Labels: {len(set(self.labels_))}")
        print(f"Most Common Cluster Size: {sizes.most_common(10)}") 
        print(f"Number of Singletons: {sum(1 for c in sizes.values() if c == 1)}")
        print(f"Largest Cluster: {max(sizes.values())} documents, Smallest Cluster: {min(sizes.values())} documents")

        return dict(zip(self.doc_ids_, self.labels_))