from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.sparse import csr_matrix
from sklearn.decomposition import TruncatedSVD
import numpy as np
from sklearn.cluster import AgglomerativeClustering
from tqdm import tqdm
import warnings
from transformers import pipeline

class DocumentClusterer():
    def __init__(self,
                ngram: tuple,
                n_components: int,
                n_iter: int,
                dist_threshold: float,
                linkage: str,
                input_type: str,
                random_state: int,
                llm_model: str,
                max_tokens: int,
                n_llm_samples: int,
                prompt_type_of_doc: str):
        
        self.ngram_range = ngram
        self.n_components = n_components
        self.n_iter = n_iter
        self.dist_threshold = dist_threshold
        self.linkage = linkage
        self.input_type = input_type
        self.random_state = random_state
        self.llm_model = llm_model
        self.max_tokens = max_tokens
        self.n_llm_samples = n_llm_samples
        self.prompt_type_of_doc = prompt_type_of_doc

        self.tfidf_ = None
        self.svd_ = None
        self.labels_ = None
        self.doc_ids_ = None

    def tfidf_vectorizer(self, documents: dict) -> csr_matrix:
        """
        Generates a Term-Document Matrix (tdm) using TF-IDF vectorization.

        This method converts a collection of raw legal documents into a sparse matrix
        representing the importance of words and n-grams across the dataset.
        Vectorizer settings (input_type, ngram range) are taken from instance attributes.

        Args:
            documents (dict): A dictionary where keys are document identifiers
            and values are the document content, filenames, or file objects,
            depending on self.input_type.

        Returns:
            scipy.sparse.csr_matrix: A Compressed Sparse Row matrix where rows
            are documents and columns are TF-IDF weighted features.

        Side effects:
            Sets self.tfidf_ to the fitted TfidfVectorizer instance.
        """
        self.tfidf_ = TfidfVectorizer(input = self.input_type,
                                    ngram_range = self.ngram_range,
                                    stop_words='english')
        
        # tdm is the term-document matrix
        self.tdm_ = self.tfidf_.fit_transform(documents.values())
        
        return self.tdm_
    
    def dim_reduction(self, term_doc_matrix:  csr_matrix) -> np.ndarray:
        '''
        Performs dimensionality reduction using Truncated SVD (Latent Semantic Analysis).

        This method reduces the high-dimensional TF-IDF matrix into a lower-dimensional
        dense representation, capturing the underlying latent topics of the documents
        while removing noise and redundancy. The number of components is clamped to
        min(self.n_components, n_features - 1) to satisfy SVD constraints.
        Reduction settings (n_components, n_iter, random_state) are taken from
        instance attributes.

        Args:
            term_doc_matrix (csr_matrix): The sparse TF-IDF matrix generated by
            tfidf_vectorizer, of shape (n_documents, n_features).

        Returns:
            np.ndarray: A dense array of shape (n_documents, safe_dim) representing
            the documents in the reduced semantic space, where safe_dim is
            min(self.n_components, n_features - 1).

        Side effects:
            Sets self.svd_ to the fitted TruncatedSVD instance.
    '''
        safe_dim = min(self.n_components, term_doc_matrix.shape[1] - 1)

        self.svd_ = TruncatedSVD(n_components = safe_dim, 
                           n_iter = self.n_iter, 
                           random_state = self.random_state)
        
        # fdm is the frequency-document matrix
        self.fdm_ = self.svd_.fit_transform(term_doc_matrix)

        return self.fdm_

    def clusterer(self, freq_doc_matrix: np.ndarray) -> np.ndarray:
        """
        Clusters documents using Agglomerative (hierarchical) Clustering.

        Groups documents hierarchically by merging clusters bottom-up until the
        linkage distance exceeds self.dist_threshold. Clustering settings
        (dist_threshold, linkage) are taken from instance attributes.

        Args:
            freq_doc_matrix (np.ndarray): Dense document matrix from dim_reduction,
            of shape (n_documents, n_components).

        Returns:
            np.ndarray: An array of integer cluster labels of shape (n_documents,),
            where each value identifies the cluster a document belongs to.

        Note:
            "ward" linkage only supports Euclidean distance. Using it with a
            different distance metric will raise a ValueError.
        """
    
        model = AgglomerativeClustering(n_clusters=None, distance_threshold = self.dist_threshold , linkage = self.linkage)
        
        cluster_labels = model.fit_predict(freq_doc_matrix)

        return cluster_labels
    
    def fit(self, documents: dict) -> dict:
        """
        Runs the full pipeline on a collection of documents.

        Args:
            documents (dict): Keys are document identifiers, values are
                raw text strings (or file paths, depending on input_type).

        Returns:
            dict: A mapping of document identifier -> cluster label.
        """
        self.doc_ids_ = list(documents.keys())

        tdm = self.tfidf_vectorizer(documents)
        fdm = self.dim_reduction(tdm)
        self.labels_ = self.clusterer(fdm)

        return dict(zip(self.doc_ids_, self.labels_))
    

    
    



        
        





