from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.sparse import csr_matrix
from sklearn.decomposition import TruncatedSVD
import numpy as np
from sklearn.cluster import AgglomerativeClustering
import ollama
from tqdm import tqdm
import warnings


class DocumentClusterer():
    def __init__(self,
                ngram: tuple,
                n_components: int,
                n_iter: int,
                dist_threshold: float,
                linkage: str,
                input_type: str,
                random_state: int,
                llm_model: str,
                n_llm_samples: int,
                prompt_type_of_doc: str):
        
        self.ngram_range = ngram
        self.n_components = n_components
        self.n_iter = n_iter
        self.dist_threshold = dist_threshold
        self.linkage = linkage
        self.input_type = input_type
        self.random_state = random_state
        self.llm_model = llm_model
        self.n_llm_samples = n_llm_samples
        self.prompt_type_of_doc = prompt_type_of_doc

        self.tfidf_ = None
        self.svd_ = None
        self.labels_ = None
        self.doc_ids_ = None

    def tfidf_vectorizer(self, documents: dict) -> csr_matrix:
        """
        Generates a Term-Document Matrix (tdm) using TF-IDF vectorization.

        This method converts a collection of raw legal documents into a sparse matrix
        representing the importance of words and n-grams across the dataset.
        Vectorizer settings (input_type, ngram range) are taken from instance attributes.

        Args:
            documents (dict): A dictionary where keys are document identifiers
            and values are the document content, filenames, or file objects,
            depending on self.input_type.

        Returns:
            scipy.sparse.csr_matrix: A Compressed Sparse Row matrix where rows
            are documents and columns are TF-IDF weighted features.

        Side effects:
            Sets self.tfidf_ to the fitted TfidfVectorizer instance.
        """
        self.tfidf_ = TfidfVectorizer(input = self.input_type,
                                    ngram_range = self.ngram_range,
                                    stop_words='english')
        
        # tdm is the term-document matrix
        self.tdm_ = self.tfidf_.fit_transform(documents.values())
        
        return self.tdm_
    
    def dim_reduction(self, term_doc_matrix:  csr_matrix) -> np.ndarray:
        '''
        Performs dimensionality reduction using Truncated SVD (Latent Semantic Analysis).

        This method reduces the high-dimensional TF-IDF matrix into a lower-dimensional
        dense representation, capturing the underlying latent topics of the documents
        while removing noise and redundancy. The number of components is clamped to
        min(self.n_components, n_features - 1) to satisfy SVD constraints.
        Reduction settings (n_components, n_iter, random_state) are taken from
        instance attributes.

        Args:
            term_doc_matrix (csr_matrix): The sparse TF-IDF matrix generated by
            tfidf_vectorizer, of shape (n_documents, n_features).

        Returns:
            np.ndarray: A dense array of shape (n_documents, safe_dim) representing
            the documents in the reduced semantic space, where safe_dim is
            min(self.n_components, n_features - 1).

        Side effects:
            Sets self.svd_ to the fitted TruncatedSVD instance.
    '''
        safe_dim = min(self.n_components, term_doc_matrix.shape[1] - 1)

        self.svd_ = TruncatedSVD(n_components = safe_dim, 
                           n_iter = self.n_iter, 
                           random_state = self.random_state)
        
        # fdm is the frequency-document matrix
        self.fdm_ = self.svd_.fit_transform(term_doc_matrix)

        return self.fdm_

    def clusterer(self, freq_doc_matrix: np.ndarray) -> np.ndarray:
        """
        Clusters documents using Agglomerative (hierarchical) Clustering.

        Groups documents hierarchically by merging clusters bottom-up until the
        linkage distance exceeds self.dist_threshold. Clustering settings
        (dist_threshold, linkage) are taken from instance attributes.

        Args:
            freq_doc_matrix (np.ndarray): Dense document matrix from dim_reduction,
            of shape (n_documents, n_components).

        Returns:
            np.ndarray: An array of integer cluster labels of shape (n_documents,),
            where each value identifies the cluster a document belongs to.

        Note:
            "ward" linkage only supports Euclidean distance. Using it with a
            different distance metric will raise a ValueError.
        """
    
        model = AgglomerativeClustering(n_clusters=None, distance_threshold = self.dist_threshold , linkage = self.linkage)
        
        cluster_labels = model.fit_predict(freq_doc_matrix)

        return cluster_labels
    
    def fit(self, documents: dict) -> dict:
        """
        Runs the full pipeline on a collection of documents.

        Args:
            documents (dict): Keys are document identifiers, values are
                raw text strings (or file paths, depending on input_type).

        Returns:
            dict: A mapping of document identifier -> cluster label.
        """
        self.doc_ids_ = list(documents.keys())

        tdm = self.tfidf_vectorizer(documents)
        fdm = self.dim_reduction(tdm)
        self.labels_ = self.clusterer(fdm)

        return dict(zip(self.doc_ids_, self.labels_))
    

    def llm_cluster_label(self) -> dict:
        """
        Uses a locally running Ollama LLM to generate a human-readable label
        for each cluster.

        Groups document identifiers by their cluster label, then samples a user defined number of documents
        per cluster and passes them to the configured Ollama
        model to produce a short descriptive label. Requires fit() to have been
        called first so that self.labels_ and self.doc_ids_ are populated.

        Returns:
            dict: A mapping of cluster_id (int) -> label (str), e.g.

        Raises:
            ValueError: If fit() has not been called and self.labels_ is None.
        """
        if self.labels_ is None:
            raise ValueError('fit() must be called before llm_cluster_label().')

        n_clusters = len(set(self.labels_))
    

        if n_clusters > 30:
            warnings.warn(
                f'llm_cluster_label() will make {n_clusters} API calls to Ollama. '
                f'This could take a while. '
                f'Consider raising dist_threshold to reduce cluster count.',
                UserWarning
            )

        clusters = {}
        for doc_id, label in zip(self.doc_ids_, self.labels_):
            clusters.setdefault(int(label), []).append(doc_id)

        generated_cluster_labels = {}
        for cluster_id, doc_ids in tqdm(clusters.items(), desc="Labelling clusters"):
            sample = doc_ids[:self.n_llm_samples] #taking a sample from cluster to reduce time for llm call
            prompt = (
                f'These {self.prompt_type_of_doc} were grouped together by a '
                'clustering algorithm:\n\n'
                + '\n'.join(sample)
                + '\n\nRespond with only a short 3-5 word label describing '
                f'what {self.prompt_type_of_doc} these are. No explanation.'
                )

            response = ollama.chat(
                model = self.llm_model,
                messages = [{'role': 'user', 'content': prompt}]
            )
            generated_cluster_labels[cluster_id] = response.message.content.strip()

        return generated_cluster_labels
    
    def error_detection(self, cluster_id: int, generated_labels: dict) -> dict:
        '''
        Uses a locally running Ollama LLM to verify whether a specific cluster
        is internally coherent.

        Samples up to self.n_llm_samples document titles from the requested cluster
        and asks the LLM whether they all belong to the same type, using the
        cluster's generated label as context. Requires fit() and llm_cluster_label()
        to have been called first.

        Args:
            cluster_id (int): The ID of the cluster to check.
            generated_labels (dict): The output of llm_cluster_label(), mapping
            cluster_id (int) -> label (str).

        Returns:
            dict: A dictionary with the following keys:
            - 'cluster_id' (int): The cluster that was checked.
            - 'label' (str): The generated label for that cluster.
            - 'verdict' (str): The LLM's YES/NO response and one sentence explanation.
        '''
        cluster_label = generated_labels[cluster_id]

        doc_titles = [
            doc_id for doc_id, label in zip(self.doc_ids_, self.labels_)
            if int(label) == cluster_id
        ]
        sample = doc_titles[:self.n_llm_samples]

        checking_prompt = (
            f'A clustering algorithm grouped these {self.prompt_type_of_doc} together '
            f'and labelled the cluster: "{cluster_label}".\n\n'
            + '\n'.join(sample)
            + '\n\nDo these titles all belong to the same type? '
            'Reply with YES or NO, then a one sentence explanation.'
        )

        response = ollama.chat(
            model=self.llm_model,
            messages=[{'role': 'user', 'content': checking_prompt}]
        )

        return {
            'cluster_id': cluster_id,
            'label': cluster_label,
            'verdict': response.message.content.strip()
        }



        
        





